"""
Middleware Example

This example demonstrates:
1. Creating custom middleware
2. Building middleware pipelines
3. Pre and post-processing
4. Logging, caching, rate limiting, and validation
"""

import asyncio
import logging
from lightagent import (
    Agent,
    AgentConfig,
    MiddlewareManager,
    LoggingMiddleware,
    RateLimitMiddleware,
    CacheMiddleware,
    ValidationMiddleware,
    RetryMiddleware,
    FunctionBuilder,
    MockAdapter,
    ModelConfig,
    BaseMiddleware,
    MiddlewareContext,
    MiddlewarePhase
)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)


# Custom middleware: Profiling
class ProfilingMiddleware(BaseMiddleware):
    """Profile agent execution time"""

    name = "profiling_middleware"

    def __init__(self):
        super().__init__()
        self.start_time = None

    async def process_pre(self, context: MiddlewareContext) -> MiddlewareContext:
        import time
        self.start_time = time.time()
        context.metadata["profiling_start"] = self.start_time
        return context

    async def process_post(self, context: MiddlewareContext) -> MiddlewareContext:
        if self.start_time:
            import time
            elapsed = time.time() - self.start_time
            context.metadata["execution_time"] = elapsed
            print(f"[PROFILING] Execution time: {elapsed:.3f}s")
        return context


# Custom middleware: Content filter
class ContentFilterMiddleware(BaseMiddleware):
    """Filter sensitive content"""

    name = "content_filter_middleware"

    def __init__(self, blocked_words: list = None):
        super().__init__()
        self.blocked_words = blocked_words or ["secret", "password", "api_key"]

    async def process_pre(self, context: MiddlewareContext) -> MiddlewareContext:
        """Check for blocked words in input"""
        message_lower = context.message.lower()

        for word in self.blocked_words:
            if word in message_lower:
                print(f"[FILTER] Blocked word detected: {word}")
                context.message = "Content filtered due to sensitive information"
                break

        return context

    async def process_post(self, context: MiddlewareContext) -> MiddlewareContext:
        """Check for blocked words in output"""
        if context.response_data and "response" in context.response_data:
            response = context.response_data["response"]
            response_lower = response.lower()

            for word in self.blocked_words:
                if word in response_lower:
                    print(f"[FILTER] Blocked word in response: {word}")
                    context.response_data["response"] = "[CONTENT FILTERED]"
                    break

        return context


# Custom middleware: Input transformation
class TransformationMiddleware(BaseMiddleware):
    """Transform input/output"""

    name = "transformation_middleware"

    async def process_pre(self, context: MiddlewareContext) -> MiddlewareContext:
        """Prepend context to message"""
        context.message = f"[User Request] {context.message}"
        return context

    async def process_post(self, context: MiddlewareContext) -> MiddlewareContext:
        """Append signature to response"""
        if context.response_data and "response" in context.response_data:
            original_response = context.response_data["response"]
            context.response_data["response"] = f"{original_response}\n\n[Generated by LightAgent]"

        return context


# Define a sample function
async def get_info(topic: str) -> str:
    """
    Get information about a topic

    Args:
        topic: Topic to get information about

    Returns:
        Information about the topic
    """
    import asyncio
    await asyncio.sleep(0.5)  # Simulate work

    info_db = {
        "python": "Python is a high-level programming language",
        "agent": "An agent is an autonomous entity that can perceive and act",
        "middleware": "Middleware is software that provides services to applications"
    }

    return info_db.get(topic.lower(), f"No information available about '{topic}'")


async def main():
    # Create model adapter
    model_config = ModelConfig(model_name="gpt-3.5-turbo")
    model_adapter = MockAdapter(config=model_config)

    # Create tool
    info_tool = FunctionBuilder.create_tool(
        get_info,
        name="get_info",
        description="Get information about a topic"
    )

    # Create middleware manager
    middleware_manager = MiddlewareManager()

    # Add middleware (order matters!)
    middleware_manager.add(LoggingMiddleware(), position="before")
    middleware_manager.add(ProfilingMiddleware())
    middleware_manager.add(ContentFilterMiddleware(blocked_words=["secret", "password"]))
    middleware_manager.add(TransformationMiddleware())
    middleware_manager.add(ValidationMiddleware(max_length=1000))
    middleware_manager.add(CacheMiddleware(ttl_seconds=60))
    middleware_manager.add(RetryMiddleware(max_retries=2))

    # Configure agent with middleware
    agent_config = AgentConfig(
        name="assistant",
        description="Assistant with middleware pipeline",
        system_prompt="You are a helpful assistant. Use the get_info tool when asked about specific topics.",
        tools=["get_info"],
        max_iterations=5,
        enable_middleware=True
    )

    # Create agent
    agent = Agent(
        config=agent_config,
        model_adapter=model_adapter,
        middlewares=middleware_manager
    )

    agent.add_tool(info_tool)

    # Initialize agent (this initializes middleware)
    await agent.initialize()

    print("=== Middleware Pipeline Active ===\n")
    print("Active middleware:")
    for i, mw in enumerate(middleware_manager.pre_middlewares):
        print(f"  {i+1}. {getattr(mw, 'name', 'unknown')} (pre)")
    print()

    # Example 1: Normal request
    print("=== Example 1: Normal Request ===")
    result = await agent.run("Tell me about Python")
    print(f"Response: {result['response']}\n")

    # Example 2: Cached request (should be faster)
    print("=== Example 2: Cached Request (Same query) ===")
    result = await agent.run("Tell me about Python")
    print(f"Response: {result['response'][:100]}...\n")

    # Example 3: Tool call with middleware
    print("=== Example 3: Tool Call with Middleware ===")
    result = await agent.run("What is an agent?")
    print(f"Response: {result['response']}\n")

    # Example 4: Content filtering
    print("=== Example 4: Content Filtering ===")
    result = await agent.run("Tell me about secret information")
    print(f"Response: {result['response']}\n")

    # Example 5: Validation (too long message)
    print("=== Example 5: Validation (Long Message) ===")
    long_message = "Tell me about " + "very " * 1000 + "Python"
    try:
        result = await agent.run(long_message)
        print(f"Response: {result['response']}")
    except Exception as e:
        print(f"Validation error: {e}\n")

    # Show execution metadata
    print("=== Execution Metadata ===")
    context = agent.get_context()
    print(f"Session ID: {context.session_id}")
    print(f"Conversation turns: {len(context.conversation_history)}")
    print(f"Total iterations: {sum(turn.get('iterations', 0) for turn in context.conversation_history if isinstance(turn, dict))}")


if __name__ == "__main__":
    asyncio.run(main())
